name: Build Rust Lambda (x86_64 MUSL)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-x86-musl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo registry & target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-x86_64-musl-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-x86_64-musl-

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add MUSL target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Install MUSL tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Build release (musl)
        run: |
          cargo build --release --target x86_64-unknown-linux-musl --bin url2pdf

      - name: Package into lambda zip
        run: |
          BINARY=url2pdf
          OUT=out
          rm -rf $OUT && mkdir -p $OUT
          cp target/x86_64-unknown-linux-musl/release/$BINARY $OUT/bootstrap
          chmod +x $OUT/bootstrap
          cd $OUT && zip ../lambda-x86_64.zip bootstrap

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: url2pdf
          path: out/
